# Looping Structures

1. Write a Python program to print the numbers from 1 to 10 using a for loop.

In [1]:
for i in range(1,11):
  print(i)

1
2
3
4
5
6
7
8
9
10

2. Write a Python program to print the numbers from 20 to 1 using a while loop.

In [3]:
i = 20
while i>= 1:
  print(i,end=' ')
  i-=1

20 19 18 17 16 15 14 13 12 11 10 9 8 7 6 5 4 3 2 1

Write a program to print even numbers from 1 to 10.

In [4]:
for i in range(2,11):
  if i % 2 ==0:
    print(i, end=' ')

2 4 6 8 10

4. Write a program that prompts the user to enter a number n and prints all the  numbers from 1 to n.

In [6]:
n = int(input("Enter the n number to print upto it: "))
for i in range(1,n+1):
  print(i, end=' ')

Enter the n number to print upto it: 5
1 2 3 4 5

 Write a program that prompts the user to enter a number n, and then prints all the  odd numbers between 1 and n.

In [7]:
n = int(input("Enter the n number to print upto it: "))

print(f"The odds number from 1 to {n} ")
for i in range(1,n+1):
  if i % 2 != 0:
    print(i, end=' ')

Enter the n number to print upto it: 100
The odds number from 1 to 100
1 3 5 7 9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95 97 99

6. Write a program that prints 'Happy Birthday!' five times on screen.

In [8]:
for i in range(5):
  print("Happy Birthday!")

Happy Birthday!
Happy Birthday!
Happy Birthday!
Happy Birthday!
Happy Birthday!

 7. Write a program that takes a number n as input from the user and generates the first  n terms of the series formed by squaring the natural numbers.

In [9]:
n = int(input("Enter n number: "))
print(f"The square of number from 1 to {n}")
for i in range(1,n+1):
  print(i**2, end=' ')

Enter n number: 5
The square of number from 1 to 5
1 4 9 16 25

8. Write a program that prompts the user to input a number and prints its multiplication  table.

In [10]:
n = int(input("Enter the n number for its multiplication table: "))

print(f"The Multiplication Table of {n}: ")
for i in range(1,11):
  print(f"{n} * {i} = {n*i}")

Enter the n number for its multiplication table: 5
The Multiplication Table of 5:
5 * 1 = 5
5 * 2 = 10
5 * 3 = 15
5 * 4 = 20
5 * 5 = 25
5 * 6 = 30
5 * 7 = 35
5 * 8 = 40
5 * 9 = 45
5 * 10 = 50

Write a Python program to print the first 8 terms of an arithmetic progression starting  with 3 and having a common difference of 4.

In [11]:
fterm = 3
cd = 4
print("The first 8 terms of aithemetic progression are: ")
for i in range(8):
  print(fterm + i* cd, end=' ')

The first 8 terms of aithemetic progression are:
3 7 11 15 19 23 27 31

10. Write a Python program to print the first 6 terms of a geometric sequence starting
with 2 and having a common ratio of 3.

In [12]:
fterm = 2
cr = 3
print("The first 6 term of geometric sequence are: ")
for i in range(6):
  print(fterm * (cr**i), end=' ')

The first 6 term of geometric sequence are:
2 6 18 54 162 486

11. Write a program that asks the user for a positive integer value. The program should  calculate the sum of all the integers from 1 up to the number entered. For example, if  the user enters 20, the loop will find the sum of 1, 2, 3, 4, ... 20.

In [15]:
n = int(input("Enter the n term to sum upto it: "))
print(f"The sum upto {n} is: ",end='')
sum  = 0
for i in range(1,n+1):
  sum+= i

print(sum)

Enter the n term to sum upto it: 20
The sum upto 20 is: 210

write a program that takes a positive integer N as input and calculates the sum of  the reciprocals of all numbers from 1 up to N. The program should display the final sum.
Output of the program should be like:  
Enter a positive integer: 5  
The sum of reciprocals from 1 to 5 is: 2.28

In [19]:
n = int(input("Enter the n term to sum its recipocal upto: "))
print(f"The reciprocal sum from 1 to {n} is: ",end='')
sum = 0
for i in range(1,n+1):
  sum += (1/i)

print(round(sum,2))

Enter the n term to sum its recipocal upto: 5
The reciprocal sum from 1 to 5 is: 2.28

13. Write a program that prompts the user to enter a number and repeats this process 5  times. The program should accumulate the numbers entered and then display the final  running total.

In [20]:
total = 0
for i in range(5):
  total += int(input("Enter a number: "))

print(f"Final running total is: {total}")

Enter a number: 10
Enter a number: 20
Enter a number: 30
Enter a number: 40
Enter a number: 50
Final running total is: 150

14. Write a program that prompts the user to enter a positive integer and calculates its  factorial. The factorial of a positive integer 'n' is denoted as 'n!' and is calculated by  multiplying all the integers from 1 to 'n' together. For example, the factorial of 5  (denoted as 5!) is calculated as 1 x 2 x 3 x 4 x 5.

In [24]:
n = int(input("Enter the number to finds its factorial: "))

fact = 1
if n < 0:
  print("The factorial of negative number does not exist.")
elif n== 0:
  print("The factorial 0 is 1")
else:
  for i in range(1,n+1):
    fact *= i
  print(f"The factorial of {n} is: {fact}")

Enter the number to finds its factorial: 5
The factorial of 5 is: 120

15. Write a Python program that prompts the user to enter a base number and an  exponent, and then calculates the power of the base to the exponent. The program  should not use the exponentiation operator (**) or the math.pow() function. The  program should handle both positive and negative exponents.

In [27]:
base = float(input("Enter the base number: "))
exponent = int(input("Enter the exponent: "))

result = 1
abs_exp = abs(exponent)
for _ in range(abs_exp):
  result*=base

if exponent<0:
  result = 1/ result

print(f"{base:.0f} raised to the power of {exponent} is {result:.2f}")

Enter the base number: 2
Enter the exponent: 5
2 raised to the power of 5 is 32.00